log_path: logs
bert_model: monologg/kobert
train_data_path: data/train.txt
val_data_path: data/val.txt
test_data_path: data/test.txt
max_len: 256
train_batch_size: 32
eval_batch_size: 32
dropout_rate: 0.1
gpus: 1
epochs: 3
task: bert_spacing
